# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_add_construction_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='exact street address'),
        ),
    ]
